### ISSUE TITLE
Feature request: change different settings in several files at a time

### ISSUE THREAD

**Issue by jdumas** [benweier/PresetCommand#6]
Hi,

It would be nice if it were possible to change different settings in multiple files at the same time. E.g. having a preset to switch between a dark and light theme, I want to modify the color theme in multiple files (for example markdown files use a different color scheme stored in a different setting file).

To this end, one could imagine a new field whose argument is a list or a dict, which contains the necessary "settings/file" for each of the concerned files.

**Comment by maxim** [comment]
+1, I am the self-proclaimed biggest fan of this plugin and this would make it more awesome (coincidentally, also because of markdown). Right now I have separate markdown preset and I have to switch 2 separate presets every time I go light/dark.

**Comment by benweier** [comment]
Thanks guys, I'll work on adding support for multiple settings files. I may end up introducing a breaking change to the current preset structure and will end up looking something like this

```json
{
  "name": "Multifile",
  "description": "Multiple files example",
  "settings": {
    "file-1.sublime-settings": {
      "theme" ...
      "color" ...
      etc
    },
    "file-2.sublime-settings": {
      "theme" ...
      "color" ...
      etc
    }
  }
}
```

The difference is the `file` value from your current presets will become the "key" for each of your list of settings for that file.

**Comment by jdumas** [comment]
That's fine by me. To alleviate the effect of the breaking change, you can detect if the key corresponds to an existing file on the disk, and warn the user about the API change if that is not the case.

**Comment by benweier** [comment]
A `2.0` branch will be going up soon with support for multiple settings files. Before this gets merged, I have a pending [PR](https://github.com/wbond/package_control_channel/pull/5993) for Package Control to switch Preset Command to tags. This will allow me to tag version releases and display messages to users when they upgrade reminding them about the schema change.

**Comment by benweier** [comment]
@jdumas @maxim
`2.0.0` has just been published and should hit Package Control soon. Let me know if you have any issues or other requests!

**Comment by maxim** [comment]
Superb work Ben, very much appreciated. A new level of awesome.
